### ISSUE TITLE
Adaptations to run pmctrack with different ERA5 data

### ISSUE THREAD

**Issue by pst019** [dennissergeev/pmctrack#25]
The ERA5 data utilized here is in some respects different from the testdata:
- different order of the dimensions (time, plev, lat, lon).
- different names of the dimensions
- the plev dimension starts at the surface
- the plev dimension is given in Pascal
- the units do not have a scale_factor and an offset
- the file names are different
- the variables on pressure levels are stored in the same file

The adaptations are in the following folder. I did not test if the results are meaningful.
[test_patrick.zip](https://github.com/dennissergeev/pmctrack/files/3897730/test_patrick.zip)

**Comment by dennissergeev** [comment]
Thanks @pst019!

I am a bit puzzled why this data are organised so differently to those obtained from CDS archive. Where did you get these data?

In any case I will try to incorporate your changes by making the input interface more abstract.

**Comment by pst019** [comment]
I retrieved the ERA5 data from the ECMWF computing facilities via MARS request.

**Comment by pst019** [comment]
Another difference:
- daily instead of monthly data.
I therefore adapted in main.f90:
!        if (idt_pair(2)%month /= idt_pair(1)%month .and. kt2 == 2) then
        if (idt_pair(2)%day /= idt_pair(1)%day .and. kt2 == 2) then

**Comment by dennissergeev** [comment]
OK, thanks! I guess we can add a few switches to `settings.conf` to account for this...

**Comment by dennissergeev** [comment]
Addressed in fc744fe07eb5e6bcb217d3e6a4772e480f209b99
